name: Setup Build Environment
description: Install platform-specific build dependencies

runs:
  using: composite
  steps:
    - name: Setup MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          git
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-metis
          unzip

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      shell: bash
      env:
        HOMEBREW_NO_INSTALL_UPGRADE: 1
      run: |
        brew install gcc metis cmake ninja
